### ISSUE TITLE
incorrect .sell syntax crashes script

### ISSUE THREAD

**Issue by VTSTech** [Veritas83/Minecraft.SNAPSHOT.Commands.Mod#3]
[19:27:25] [Server thread/INFO]: <silverfish313> .sell Cocoa Beans 1
Traceback (most recent call last):
  File "C:\Users\Redacted\Desktop\MCSRV_112SNAPSHOT\commands.by.YT_Veritas0923.py", line 840, in <module>
    sellqty = int(tmp[6])
ValueError: invalid literal for int() with base 10: 'Beans'

**Comment by jaythaceo** [comment]
You are using a PC correct?

**Comment by VTSTech** [comment]
Yes

**Comment by jaythaceo** [comment]
Haven't read all of the code but this is a general answer. 
The string passed to int() should only contain digits:
That's usually the reason for those errors we may need traceback run make some tests

**Comment by VTSTech** [comment]
https://github.com/Veritas83/Minecraft.SNAPSHOT.Commands.Mod/commit/fbbf6d855debb89c22afc7627d9af981403e7175

**Comment by VTSTech** [comment]
```
					if type(tmp[6]) is int:
						sellqty = int(tmp[6])
					else:
						sellqty = 1
					if sellqty > 1024:
						sellqty = 1024
```
